server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ch-redleaf/springcloud-config.git #GitHub上面的git仓库名字
            ####搜索目录
          search-paths:
            - springcloud-config
#          skip-ssl-validation: true
          username: ch-redleaf
          password: xiaohan950118
          ####读取分支
      label: master

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
            defaultZone: http://localhost:7001/eureka
      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    instance-id: config-center
    prefer-ip-address: true

